### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'grammalecte-cli.py'

### ISSUE THREAD

**Issue by JulienPalard** [vpoulailleau/pygrammalecte#1]
Got this error here: https://github.com/python/python-docs-fr/pull/1474/checks?check_run_id=1439453273

any hint?

**Comment by vpoulailleau** [comment]
Faut que je regarde…

Grammalecte s'installe bien, selon le log, avec :

```python
    subprocess.check_call(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            str(tmpdirname / f"Grammalecte-fr-v{version}"),
        ]
    )
```

Par contre, j'ai vu que tu (@JulienPalard) appelais directement le Python de l'environnement virtuel sans activer l'environnement virtuel. Je n'ai jamais fait ça. Grammalecte installe un exécutable (`grammalecte-cli.py`, le fameux not found), mais sans l'environnement virtuel activé, je ne sais pas où il le met, mais visiblement pas dans le PATH.

À court terme, tu peux essayer d'activer l'environnement virtuel, ça devrait résoudre ton problème. Par contre il faut que j'investigue cette histoire :wink:

**Comment by JulienPalard** [comment]
Ah oui je fais toujours ca dans mes cron/scripts/... (Le coup d'appeler Python sans activer le venv).

L'activation du venv ne fait que changer le path, donc ça doit bien résoudre le souci. Bien vu ! Dans mes cas habituels ça ne pose pas de souci, les imports fonctionnent :)

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------

**Comment by JulienPalard** [comment]
Pour résoudre le "souci" tu pourrais importer, plutôt qu'exécuter, `grammalecte-cli.py`.

Mais ce n'est pas un vrai souci, c'est surtout moi qui n'ai pas activé le venv, j'assume.
