### ISSUE TITLE
pygrammalecte n'est pas compatible avec Google Colab

### ISSUE THREAD

**Issue by Achuttarsing** [vpoulailleau/pygrammalecte#3]
Impossible d'installer pygrammalect sur un notebook Colab. 

J'ai essayé :
`!python3 -m pip install pygrammalecte` et `!pip install pygrammalecte`

et j'obtiens le message suivant : 
**_ERROR: Could not find a version that satisfies the requirement pygrammalecte (from versions: none)
ERROR: No matching distribution found for pygrammalecte_**

**Comment by vpoulailleau** [comment]
Quelle est la version de Python à disposition sur Colab ?

`!python3 --version`

Sur le README de `pygrammalecte`, il est mentionné qu'il faut au moins Python 3.7, ce qui pourrait expliquer ce message d'erreur avec une version inférieure.

Si j'en crois https://colab.research.google.com/github/cs231n/cs231n.github.io/blob/master/python-colab.ipynb :

> Note that as of April 2020, Colab uses Python 3.6.9 which should run everything without any errors.

Python 3.6 est « vieillot » et ne reçoit plus de correction de bug, uniquement des mises à jours de sécurité (tout comme Python 3.7). Python 3.7 est sorti il y a un an et demi, et est requis pour faire fonctionner `pygrammalecte`. `pygrammalecte` fonctionne avec Python 3.7, 3.8, 3.9. `pygrammalecte` utilise les `dataclass` qui sont apparues avec Python 3.7 (https://github.com/vpoulailleau/pygrammalecte/blob/master/pygrammalecte/pygrammalecte.py#L15 et https://realpython.com/python-data-classes/)

Est-il possible de passer à une version de Python plus récente ? (une piste peut-être : https://stackoverflow.com/questions/63168301/how-to-change-the-python-version-from-default-3-5-to-3-8-of-google-colab ou encore https://stackoverflow.com/questions/52467489/is-there-a-way-to-use-python-3-5-instead-of-3-6/52472939#52472939)

**Comment by Achuttarsing** [comment]
Ok ! merci pour ta réactivité ! Je vais explorer les pistes que tu m'as données. Il va falloir que je trouve une solution car je pense que Google n'est pas prêt d'upgrader ses outils.

**Comment by alix-tz** [comment]
Bonjour, j'ai utilisé Pygrammalecte sans problème sur Colab, avec la commande `!pip install pygrammalecte` et sans avoir préalablement modifié le setup de mon notebook. 👍

**Comment by Achuttarsing** [comment]
Bon à savoir ! Apparement colab est passé à python 3.7 entre temps !

**Comment by vpoulailleau** [comment]
Super nouvelle !
