### ISSUE TITLE
Changer l'ordre des suggestions

### ISSUE THREAD

**Issue by maky-hnou** [vpoulailleau/pygrammalecte#4]
Est-il possible de changer l'ordre des mots dans la suggestion?  
Par exemple, ici on a: `(Suggestions : compliquées, compliqués, compliqué, compliquée)`. 
1- Selon quoi les suggestions sont-elles organisées?
2- Peut-on changer l'ordre des suggestions? (par exp: on aura: `(Suggestions :  compliqué, compliquée, compliquées, compliqués)` au lieu de `(Suggestions : compliquées, compliqués, compliqué, compliquée)`)  
Merci

**Comment by vpoulailleau** [comment]
C'est une excellente question pour l'ordre des suggestions. Je n'ai pas la réponse car ce projet (`pygrammalecte`) n'est qu'une surcouche à `Grammalecte` que je ne trouvais pas assez facile d'utilisation à mon goût. Je ne connais pas le critère de tri actuel, il faudrait poser la question sur https://grammalecte.net/forum.php?prj=fr

Quant à changer l'ordre, je ne vois pas comment on peut changer le critère de tri, il faudrait poser la question sur le forum.

Je vous encourage à poser la même question sur le forum en précisant que vous utilisez `Grammalecte` en ligne de commande. Pour l'instant, c'est `Grammalecte` en version 1.12.0 qui est utilisé par `pygrammalecte` mais je viens de voir qu'une version 2.0.0 vient d'être publiée.

Je ne peux malheureusement pas fournir plus d'information, ne connaissant pas le fonctionnement détaillé de `Grammalecte`.

**Comment by maky-hnou** [comment]
Merci pour la clarification.  
Je vais poser la question dans le forum de grammalecte.

**Comment by vpoulailleau** [comment]
De rien, bonne continuation.
